### ISSUE TITLE
Is it possible to underline text?

### ISSUE THREAD

**Issue by statler** [arklumpus/VectSharp#10]
It is probably obvious, but I could not figure out how to achieve this - or is it assumed the underline can be created as a separate stroke?

**Comment by arklumpus** [comment]
Text can now be "officially" underlined as of version 2.1.0! See the [release notes for 2.1.0](https://github.com/arklumpus/VectSharp/releases/tag/v2.1.0) for a few examples.

<p align="center"><img src="https://user-images.githubusercontent.com/32712606/151072872-4a47ae0e-a93f-470e-9334-92ec0eaf6a85.svg" height="400"></p>
