### ISSUE TITLE
ExCSS-Core is marked as deprecated

### ISSUE THREAD

**Issue by dstj** [arklumpus/VectSharp#12]
Hi,

FYI, when looking at the dependencies for VectSharp.SVG, I noticed that [`ExCSS-Core`](https://www.nuget.org/packages/ExCSS-Core/) is now marked as **Deprecated**

> Suggested Alternatives
[ExCSS](https://www.nuget.org/packages/ExCSS/)

**Comment by arklumpus** [comment]
Hi, thanks for pointing this out! I will make sure to update this when I publish the LGPL release. I'm finishing my PhD thesis now, so I really don't have much time to spare 😅

**Comment by dstj** [comment]
@arklumpus
Was simple enough, I created a PR for you: #13

Good luck with your thesis!! 💪

**Comment by arklumpus** [comment]
Great, thanks!
