### ISSUE TITLE
VectSharp.Markdown depends on Highlight.NoEngine, but it depends on old version of VectSharp

### ISSUE THREAD

**Issue by AlexanderMagdysyuk** [arklumpus/VectSharp#15]
It is not a problem in the case of stable API, but can be a problem in the future. Can we change this? For example - make Highlight.NoEngine part of the VectSharp project?

**Comment by arklumpus** [comment]
Hi, I'm keeping Highlight.NoEngine separate because it makes it easier for copyright/licensing... In any case, it only depends on VectSharp for colour stuff and that part should be stable!
