### ISSUE TITLE
Can not use ParseTABLE for HTML table with some css styles.

### ISSUE THREAD

**Issue by zydjohnHotmail** [arklumpus/VectSharp#18]
Hello:
I have some old C# code to parse HTML table, like this:
List<List<(string Contents, bool IsHeader)>> table = ParseHTMLTable(html_table);
The ParseHTMLTable function is defined as below:
static List<List<(string Contents, bool IsHeader)>>? ParseHTMLTable(string html)
{
    try
    {
if (html.Contains("<table style="))
{
    XDocument doc = XDocument.Parse(html);
    XElement table = doc.Element(XName.Get("table"));
    return (from row in table.Elements(XName.Get("tr"))
    select (from cell in row.Elements()
    where cell.Name == XName.Get("td") || cell.Name == XName.Get("th")
    select (string.Concat(from el in cell.Nodes() select el.ToString(SaveOptions.DisableFormatting)),
    cell.Name == XName.Get("th"))).ToList()).ToList();
}
    }
    catch (System.Xml.XmlException ex)
    {
Debug.Print("[ParseHTMLTable]" + ex.Message);
    }
    return null;
}
The code works when I use simple HTML table with any css style.
But when I want to use the following HTML table with simple CSS style, it returns null.

<table style="width:100%">
  <tr>
    <th>#</th>
    <th>Goal</th>
    <th>Time</th>
    <th>Score</th>
  </tr>
  <tr>
    <td style="border: 3px solid red; ">1</td>
    <td style="border: 3px solid red; ">Otavio</td>
    <td style="border: 3px solid red; ">24:10</td>
    <td style="border: 3px solid red; ">1-0</td>
  </tr>
  <tr>
    <td>2</td>
    <td>L. Diaz</td>
    <td>36:50</td>
    <td>2-0</td>
  </tr>
  <tr>
    <td>3</td>
    <td>M. Taremi</td>
    <td>77:20</td>
    <td>3-0</td>
  </tr>
  <tr>
    <td>4</td>
    <td>Riccieli</td>
    <td>90:51</td>
    <td>3-1</td>
  </tr>
  <tr>
</table>
</tr>

Any suggestion on how to change the code to work with the HTML table with some CSS style?

**Comment by zydjohnHotmail** [comment]
Note:
Github convert my HTML table, so I can't see the HTML code.
I tried to use code to show it:
`<table style="width:100%">
  <tr>
    <th>#</th>
    <th>Goal</th>
    <th>Time</th>
    <th>Score</th>
  </tr>
  <tr>
    <td style="border: 3px solid red; ">1</td>
    <td style="border: 3px solid red; ">Otavio</td>
    <td style="border: 3px solid red; ">24:10</td>
    <td style="border: 3px solid red; ">1-0</td>
  </tr>
  <tr>
    <td>2</td>
    <td>L. Diaz</td>
    <td>36:50</td>
    <td>2-0</td>
  </tr>
  <tr>
    <td>3</td>
    <td>M. Taremi</td>
    <td>77:20</td>
    <td>3-0</td>
  </tr>
  <tr>
    <td>4</td>
    <td>Riccieli</td>
    <td>90:51</td>
    <td>3-1</td>
  </tr>
  <tr>
</table>
</tr>`

**Comment by arklumpus** [comment]
Hi! From what I see, the problem is with the table's HTML code, not with the code (or CSS).

If you look at the last three lines of your table's HTML, you will see:

```
...
 <tr>
</table>
</tr>
```

The `<tr>` and `</tr>` shouldn't be there. If you replace these three lines with just `</table>`, it works.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your help, I fixed this issue.  But I found yet another issue, which is related to this one.  But I will raise another issue with necessary information.
Thanks,
