### ISSUE TITLE
HTML Table style is gone when using the repo to Render Row.

### ISSUE THREAD

**Issue by zydjohnHotmail** [arklumpus/VectSharp#19]
Hello:
I have a HTML table with has red border with one row of the table, it looks good in browser.
However, I want to use the repo to draw the HTML table in a PNG format picture on top of a background picture.
But I found the Render Row function seems remove all style, it becomes style-less.
The following is related C# code:
        public static async Task HTML_Table_Show_Data0
        (string html_table, string background_png, string png_file1)
        {
            try
            {
                List<List<(string Contents, bool IsHeader)>> table =
                    ParseHTMLTable(html_table);
                Font titleFont =
                    new(ResolveFontFamily(StandardFontFamilies.HelveticaBold), 16);
                Font regularFont =
                    new(ResolveFontFamily(StandardFontFamilies.Helvetica), 14);
                double pageWidth = 1280;
                double pageMarginTop = 20;
                double pageMarginBottom = 20;
                double pageMarginLeft = 100;
                double pageMarginRight = 100;
                Page pag = new(pageWidth, 0);
                double availableWidth = 
                    pageWidth - pageMarginLeft - pageMarginRight;
                double[] columnWidths = GetColumnWidths(table, availableWidth, titleFont, regularFont);
                double tableHeight = 0;
                pag.Graphics.Translate(pageMarginLeft, pageMarginTop);
                pag.Graphics.Save();
                for (int i = 0; i < table.Count; i++)
                {
                    double rowHeight = RenderRow(table[i], columnWidths, titleFont, regularFont, pag.Graphics, i < table.Count - 1);
                    tableHeight += rowHeight;
                    pag.Graphics.Translate(0, rowHeight);
                }
                pag.Graphics.Restore();
                double currX = 0;
                for (int i = 0; i < columnWidths.Length - 1; i++)
                {
                    pag.Graphics.StrokePath(new GraphicsPath().MoveTo(currX + columnWidths[i], 0).LineTo(currX + columnWidths[i], tableHeight), Colours.Black);
                    currX += columnWidths[i];
                }
                pag.Graphics.StrokeRectangle(0, 0, availableWidth, tableHeight, Colours.Black);
                pag.Height = tableHeight + pageMarginTop + pageMarginBottom;
                Page containerPage = new(P1280_Width, P1280_Height) { Background = Colours.White };
                RasterImageFile image = new(background_png);
                containerPage.Graphics.DrawRasterImage(0, 0, 1280, 720, image);
                containerPage.Graphics.DrawGraphics(0, (720 - pag.Height) * 0.5, pag.Graphics);
                containerPage.SaveAsPNG(png_file1);
            }
            catch (FileNotFoundException ex)
            {
                Debug.Print(ex.Message);
                await Task.Delay(1000);
            }
        }

        static double RenderRow(List<(string Contents, bool IsHeader)> row, double[] columnWidths,
        Font titleFont, Font regularFont, Graphics graphics, bool drawBottomBorder)
        {
            double cellMarginLeft = 5;
            double cellMarginRight = 5;
            double cellMarginTop = 5;
            double cellMarginBottom = 5;
            List<(Graphics Buffer, double Height)> cellGraphics = new();
            double rowHeight = 0;
            for (int i = 0; i < row.Count; i++)
            {
                Graphics cellBuffer = new();
                double cellWidth = columnWidths[i] - cellMarginLeft - cellMarginRight;
                double height = RenderCell(row[i].Contents, cellWidth,
                    row[i].IsHeader ? titleFont : regularFont, cellBuffer);
                rowHeight = Math.Max(rowHeight, height);
                cellGraphics.Add((cellBuffer, height));
            }
            double totalRowHeight = rowHeight + cellMarginTop + cellMarginBottom;
            if (drawBottomBorder)
            {
                graphics.StrokePath(new GraphicsPath().MoveTo(0, totalRowHeight).LineTo(columnWidths.Sum(),
                    totalRowHeight), Colours.Black);
            }
            graphics.Save();
            graphics.Translate(cellMarginLeft, 0);
            for (int i = 0; i < cellGraphics.Count; i++)
            {
                double cellY = cellMarginTop + (rowHeight - cellGraphics[i].Height) * 0.5;
                graphics.Save();
                graphics.DrawGraphics(0, cellY, cellGraphics[i].Buffer);
                graphics.Restore();
                graphics.Translate(columnWidths[i], 0);
[StyleHTMLTable.pdf](https://github.com/arklumpus/VectSharp/files/7953008/StyleHTMLTable.pdf)
[StyleHTMLTable.pdf](https://github.com/arklumpus/VectSharp/files/7953012/StyleHTMLTable.pdf)
![Style_less_HTMLTable](https://user-images.githubusercontent.com/45263518/151422631-44e55262-79a6-41b6-8beb-ad9a8491a891.png)
![StyleHTMLTable](https://user-images.githubusercontent.com/45263518/151422746-d49a7048-04af-4888-8786-04de21cd9821.png)

            }
            graphics.Restore();
            return totalRowHeight;
        }

I also attach the background PNG picture, the HTML table source code, the styled HTML table appear in browser, the result style-less HTML table on top of the background picture.

**Comment by zydjohnHotmail** [comment]
Hi,
I forgot the background_png file.
Here it comes.
![Background_PNG](https://user-images.githubusercontent.com/45263518/151424178-6742cf52-1f8e-4cf3-97f9-159d5f63015f.png)

**Comment by arklumpus** [comment]
Hi! Yes, that's expected - that code does nothing to parse or interpret the CSS style. If you want to use that information, you will need a library to interpret the CSS (e.g. [ExCSS](https://github.com/TylerBrinks/ExCSS)), but you will have to figure out what kind of style/formatting you expect and how you want to apply it (e.g.: are you only expecting coloured borders? Will the thickness of the border change as well? What about the background of the cell?)...

In any case, if you need to render arbitrarily complex HTML tables, your best bet is probably to use some sort of web browser control, rather than trying to implement the parser and renderer yourself... If you are in control of your data source, instead, you should try to make it output data in an "easier" format than an HTML table (e.g. a JSON string).

**Comment by zydjohnHotmail** [comment]
Hello:
Now, I only need to coloured borders. If you have some free time, please give me an example on how to do this with this repo.
I have no plan for arbitrarily complex HTML tables.
By the way, is it possible to create a PNG format of the HTML table, and merge with the background PNG file to make one PNG file, so I can see the HTML table with coloured borders on top of the background picture?
Thanks,

**Comment by zydjohnHotmail** [comment]
Hi,
Can forget this one, but I have yet another issue. I will open a new issue now.
