### ISSUE TITLE
Set the picture DPI?

### ISSUE THREAD

**Issue by lijianxin520** [arklumpus/VectSharp#26]
Hello, I would like to know how to set the DPI for saving pictures?

**Comment by arklumpus** [comment]
Hi, do you mean when producing raster images (e.g. PNG, JPG, etc)?

If you are using VectSharp.Raster, you can use the optional `scale` parameter to change the size in pixels of the image. For example:

```CSharp
using VectSharp;
using VectSharp.Raster;

Page pag = new Page(100, 100);

// Draw something

pag.SaveAsPNG("image.png", scale: 2);
```

In this case, the size of `image.png` will be 200x200 pixel. You cannot specify DPI in a PNG image.

If you want to change the DPI of the image that you see e.g. in a JPEG file when you right-click it to show its properties, you can do so by using VectSharp.Raster.ImageSharp and SixLabors.ImageSharp:

```CSharp
using VectSharp;
using VectSharp.Raster.ImageSharp;
using SixLabors.ImageSharp;

Page pag = new Page(100, 100);

// Draw something

Image<SixLabors.ImageSharp.PixelFormats.Rgba32> image = pag.SaveAsImage(scale: 2);

// Set horizontal DPI
image.Metadata.HorizontalResolution = 300;

// Set vertical DPI
image.Metadata.VerticalResolution = 300;

// Save as JPG
image.SaveAsJpeg("image.jpg");
```

In this case, `image.jpg` will be 200x200 pixel, and the horizontal and vertical resolution will both be 300dpi.

**Comment by lijianxin520** [comment]
Thank you very much for your help！
