### ISSUE TITLE
Translation size system to standards on pdf

### ISSUE THREAD

**Issue by lutz** [arklumpus/VectSharp#27]
Hey,
i have a question about the translation from the document model to pdf. I will generate a pdf with a standard size of `A4`. What kind of "factor" i should use to set the right page size and coordinate values for the graphic objects?
best regards
Daniel

**Comment by lutz** [comment]
Okay i found a way out. The size is in point (computer) to translate millimeter to point, i can calculate this:

`  private static double ConvertToPoint(double millimeter) => millimeter * 360.0 / 127.0;`

**Comment by arklumpus** [comment]
Hi! Normally, a PDF unit is 1/72 inches, thus to convert between VectSharp units and inches you can just divide by 72. From there, you can convert to millimetres multiplying by 25.4 (and vice versa). Thus:

```CSharp
private static double ConvertToMillimetre(double points) => points * 25.4 / 72;

private static double ConvertToPoint(double millimetre) => millimetre * 72 / 25.4;
```
This should be equivalent to your code, since obviously `360.0 / 127.0 == 72 / 25.4`.
