### ISSUE TITLE
Domain Diagram 

### ISSUE THREAD

**Issue by raffdp** [arklumpus/VectSharp#29]
Slightly off topic, but what did you use to create the domain diagram shown here as the idea - https://giorgiobianchini.com/VectSharp/

**Comment by arklumpus** [comment]
I'm afraid I just drew it by hand using Inkscape 😅

**Comment by raffdp** [comment]
Phew! I had a severe case of FOMO there thinking I was missing out on some magical tool that generated a domain API diagram like that. A diagram like that is so self explanatory and helps visualize the API so much better in your head.
