### ISSUE TITLE
Can I use this repo to generate SVG from text?

### ISSUE THREAD

**Issue by zydjohnHotmail** [arklumpus/VectSharp#3]
Hello:
I want to know if I can use this repo to generate some SVG files from simple English text, for example: "Hello World!"
Can I generate a SVG file from the text?
Thanks,

**Comment by arklumpus** [comment]
Hi, yeah, sure!

If you have just a short string, it's as simple as this:

```CSharp
using VectSharp;
using VectSharp.SVG;

// ...

    Page pag = new Page(100, 100);
    Font font = new Font(new FontFamily(FontFamily.StandardFontFamilies.Helvetica), 20);

    // You can use font.MeasureText("Hello world") to position the text or size the page more accurately

    pag.Graphics.FillText(10, 10, "Hello world!", font, Colours.Black);
    pag.SaveAsSVG("HelloWorld.svg");
```
By default, when you save the page as an SVG file, the library will include within the document a subset of the font containing only the letters in the text (similar to what happens with PDF documents). If you wish to change this, you can supply an optional `SVGContextInterpreter.TextOptions` parameter:

```CSharp
    // This will save the page as an SVG file, including the whole font file in the SVG document
    pag.SaveAsSVG("HelloWorld.svg", SVGContextInterpreter.TextOptions.EmbedFonts);

    // This will save the page as an SVG file, without including the font (which means that if the computer
    // that is used to view the image does not have the font, it might be rendered using a different font):
    pag.SaveAsSVG("HelloWorld.svg", SVGContextInterpreter.TextOptions.DoNotEmbed);

    // This will save the page as an SVG file, converting all text elements into paths:
    pag.SaveAsSVG("HelloWorld.svg", SVGContextInterpreter.TextOptions.ConvertIntoPaths);
```

If you have a longer text with paragraphs etc., you can use `VectSharp.Markdown` instead:

```CSharp
using VectSharp;
using VectSharp.SVG;
using VectSharp.Markdown;

// ...

    string documentText = System.IO.File.ReadAllText("Review.txt");

    MarkdownRenderer renderer = new MarkdownRenderer();

    // Width of the SVG document
    double pageWidth = 500;

    Page pag = renderer.RenderSinglePage(documentText, pageWidth, out _);
    pag.SaveAsSVG("Document.svg");
```

This renders the document as a single page. Alternatively, you can render it to multiple pages:

```CSharp
    // Use renderer.PageSize to set up the page size

    Document doc = renderer.Render(documentText, out _);
            
    for (int i = 0; i < doc.Pages.Count; i++)
    {
        doc.Pages[i].SaveAsSVG("Page" + i.ToString() + ".svg");
    }
```

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your code, it works.
I have yet another further request. I want to put the text in the center of the page.  I have only one page, the text is not long, but the page is rather small, it has only 700 by 300 points in WinForms designer.
How I can make sure that in the generated SVG file, the text is in the center, it can has up to 3 lines, but I don't want to split the text in the word.  For example: I don't want to split "World" into "Wor" in one line, and "ld" in the second line.
I can use fixed font, like: font12 = new("Arial", 12, FontStyle.Bold, GraphicsUnit.Point);
By the way, can I use your repo to convert SVG to PNG?
Thanks,

**Comment by arklumpus** [comment]
If you have a text that needs to flow with a maximum width constrain, the best approach would probably be the one using `VectSharp.Markdown` above (this automatically introduces newlines as necessary, without breaking any word).

Using the `RenderSinglePage` method will produce a page with the specified width and exactly the right height to contain the text (with the appropriate margins that are specified in the `MarkdownRenderer` object). If you then want to center this in a 700x300 page, you can take the size of the page produced by the renderer and use it to center it into the new page:

```CSharp
using VectSharp;
using VectSharp.SVG;
using VectSharp.Markdown;

// ...

    string documentText = <your text>

    MarkdownRenderer renderer = new MarkdownRenderer();

    // Width of the SVG document (you probably want to change this to 700)
    double pageWidth = 500;

    Page pag = renderer.RenderSinglePage(documentText, pageWidth, out _);

    // Larger page in which you want to center the text
    Page containerPage = new Page(700, 300);

    containerPage.Graphics.DrawGraphics((containerPage.Width - pag.Width) * 0.5, (containerPage.Height - pag.Height) * 0.5, pag.Graphics);

    containerPage.SaveAsSVG("Document.svg");
```

In principle, you can use VectSharp.SVG and VectSharp.Raster to load an SVG image into a `VectSharp.Page` object, and then export this to a PNG image. You will also need VectSharp.MuPDFUtils:

```CSharp
using VectSharp;
using VectSharp.SVG;
using VectSharp.Raster;
using VectSharp.MuPDFUtils;

// ...

    // Setup the SVG parser so that it can load raster images embedded within SVG documents.
    Parser.ParseImageURI = ImageURIParser.Parser(Parser.ParseSVGURI);

    // Load the SVG document in a Page object.
    Page pag = Parser.FromFile("test.svg");

    // Save the Page object as a PNG image. If you wish to increase the resolution, change the 1 to something larger.
    pag.SaveAsPNG("test.png", 1);
```

This should work for _most_ SVG images; however, SVG is a very complex format, and VectSharp does not support all of the possible things that can be done with it. The only guarantee is that opening an image that was created with VectSharp should work without issues.

If you are using .NET Framework, you probably want to read the [note about MuPDFCore and .NET Framework](https://github.com/arklumpus/MuPDFCore#note-about-mupdfcore-and-net-framework-) in the MuPDFCore repository (this comes as a dependency of VectSharp.Raster and VectSharp.MuPDFUtils), for instructions on how to make sure that the MuPDFCore DLL library ends up in the right place (you should easily notice if this is the problem). If you are using .NET Core or .NET 5 you don't need to do anything.

Also, VectSharp doesn't use the same fonts as System.Drawing, if you want to have the same font on the interface and in the SVG file, your best best is probably to get a font in TrueType format (.TTF) and use it to create both a `VectSharp.Font` and a `System.Drawing.Font`. Otherwise, the "Helvetica" font embedded in VectSharp (which is actually Nimbus Sans) and Arial should be very similar (in particular, they should have the same metrics).

**Comment by zydjohnHotmail** [comment]
Hello,
Thank you very much for your code and explanation, I created the following code according to your explanation: (C# for target .NET 5.0)

using System;
using System.Threading.Tasks;
using VectSharp;
using VectSharp.Markdown;
using VectSharp.MuPDFUtils;
using VectSharp.Raster;
using VectSharp.SVG;

namespace VectSharpText2SVG2PNG
{
    class Program
    {
        public const double Page_Width = 768;
        public const double Page_Height = 268;
        public const string Save_SVG_File = @"C:\Temp\SVGCenterText.svg";
        public const string Save_PNG_File = @"C:\Temp\SVGCenterText.png";

        public static async Task CenterTextSVG1Page()
        {
            string documentText = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.";
            MarkdownRenderer renderer = new();
            double pageWidth = Page_Width;
            Page svg_page = renderer.RenderSinglePage(documentText, pageWidth, out _);
            Page containerPage = new (800, 300);
            containerPage.Graphics.DrawGraphics((containerPage.Width - svg_page.Width) * 0.5, 
                (containerPage.Height - svg_page.Height) * 0.5, svg_page.Graphics);
            containerPage.SaveAsSVG(Save_SVG_File);
            await Task.Delay(1000);
            Parser.ParseImageURI = ImageURIParser.Parser(Parser.ParseSVGURI);
            Page parse_page = Parser.FromFile(Save_SVG_File);
            parse_page.SaveAsPNG(Save_PNG_File, 1);
        }

        static async Task Main()
        {
            await CenterTextSVG1Page();
            Console.Beep();
        }
    }
}

Now, I have 2 minor issues:
1) The font size seems to be rather small, how I can set font style and size in the program? If not the same as System.Drawing.Font, but if I can get the similar visual effect, like the size, and style, like Bold, then it is OK.
2) I want to draw the text in the center of the page, but when I look at the generated PNG file, I can see that the text is not in the center of the page.  Let me know if I understand it incorrectly.  How to change it, so the final PNG file, the text is in the center of the page.
I don't know how to upload a PNG picture in the reply yet.  If I know, I can upload a picture show you the PGN file.
Finally, thanks again for you kind help.

**Comment by zydjohnHotmail** [comment]
![SVGCenterText](https://user-images.githubusercontent.com/45263518/128992330-adec6590-e714-469b-b935-d1f15be769af.png)

**Comment by arklumpus** [comment]
Hi, first of all, you don't need to save the image as an SVG file and then load it again to save it as PNG, you can save it as SVG and PNG directly:

```CSharp
// ...
        containerPage.SaveAsSVG(Save_SVG_File);

        // Remove these:
        // await Task.Delay(1000);
        // Parser.ParseImageURI = ImageURIParser.Parser(Parser.ParseSVGURI);
        // Page parse_page = Parser.FromFile(Save_SVG_File);
        // parse_page.SaveAsPNG(Save_PNG_File, 1);

        // Do this instead:
        containerPage.SaveAsPNG(Save_PNG_File, 1);
```

1. If you want to increase the font size, you can just change the value of the `renderer.BaseFontSize` property: the default value is `9.71424`, so if you increase it e.g. to 20 you will get bigger text. You can also change the value of `renderer.RegularFontFamily` to get text in a different style (bold etc.), or you can use a properly formatted Markdown text string to get text with mixed styles. For example, this will make the text bigger and in bold:

``` CSharp
        // ...
        MarkdownRenderer renderer = new();

        renderer.BaseFontSize = 20;
        renderer.RegularFontFamily = new FontFamily(FontFamily.StandardFontFamilies.HelveticaBold);

        double pageWidth = Page_Width;
        // ...
```

2. If you want the text to be centered horizontally in the page as well as vertically, you need to manually split it into different lines and draw each line separately (the Markdownrenderer only supports left-aligned text). For example, the following might be an approach (it's not very efficient because every time it adds a word it has to measure everything again, but it should be enough to point you in the right direction, and if you're not doing this in a tight loop it might be fast enough):

```CSharp
    string documentText = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas at justo neque. Maecenas vitae tincidunt lectus. Proin vitae ex vitae sem vulputate consectetur id quis ex. Morbi vitae lectus faucibus, luctus dui et, tempus arcu. Aliquam laoreet at dui id ornare. Nulla facilisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam pellentesque sollicitudin arcu sed placerat. Aliquam vulputate tincidunt varius. Duis laoreet lorem in lectus scelerisque, quis aliquet nunc dictum. Nam consectetur sem lectus. Cras egestas elementum odio quis fermentum. Donec eu malesuada diam.
Donec vitae magna mauris. Duis mollis, orci at tincidunt luctus, ante orci scelerisque lorem, vel fringilla felis ex commodo est. Praesent sed fermentum ipsum, id dignissim libero. Nunc convallis quam at libero finibus placerat. Nunc vestibulum eros dolor, a blandit velit consectetur eget. Pellentesque pharetra, nibh vitae interdum rutrum, dolor enim ultrices elit, id fermentum sem ex non velit. Phasellus consectetur ligula tellus, a maximus nisi ornare ac.";

    // Split the text in paragraphs (i.e. at every line break)
    string[] documentParagraphs = documentText.Split(Environment.NewLine);

    // Split each paragraph into separate words
    string[][] documentWords = new string[documentParagraphs.Length][];

    for (int i = 0; i < documentParagraphs.Length; i++)
    {
        // Split at spaces. You could use a Regex matching \b for something fancier, but this should be enough.
        documentWords[i] = documentParagraphs[i].Split(' ');
    }

    // Define a font to render the text
    Font fnt = new Font(new FontFamily(FontFamily.StandardFontFamilies.Helvetica), 20);
            
    // Width of the page - the text will be able to fill it completely, so make this smaller to get a bigger margin if you need.
    double pageWidth = Page_Width;

    // Graphics surface on which we will draw the text
    Graphics textGraphics = new Graphics();

    // Current y coordinate, we will increment this as we draw the text lines
    double currY = fnt.FontSize * 1.4;
            
    // Render each paragraph separately 
    for (int i = 0; i < documentWords.Length; i++)
    {
        System.Text.StringBuilder currentLine = new System.Text.StringBuilder();
        int wordIndex = 0;

        while (wordIndex < documentWords[i].Length)
        {
            // Current text of the line buffer
            string currentLineText = currentLine.ToString();

            // Test string: let's see whether this fits in the page or not
            string testText = currentLineText + " " + documentWords[i][wordIndex];

            // Measure the test string
            Size testTextSize = fnt.MeasureText(testText);

            if (testTextSize.Width < pageWidth)
            {
                // We can append the current word and not go over the page width limit: append the current word and go on.
                currentLine.Append(" ");
                currentLine.Append(documentWords[i][wordIndex]);
            }
            else
            {
                // Appending the current word causes us to go over the page width limit: render the current line (if it's not empty) and go on.
                if (currentLine.Length > 0)
                {
                    // Measure the current line width
                    Size currentLineSize = fnt.MeasureText(currentLineText);

                    // Draw the text line centering it horizontally
                    textGraphics.FillText((pageWidth - currentLineSize.Width) * 0.5, currY, currentLineText, fnt, Colours.Black, TextBaselines.Baseline);

                    // Increase the current y coordinate
                    currY += fnt.FontSize * 1.4;
                }

                currentLine.Clear();
                currentLine.Append(documentWords[i][wordIndex]);
            }

            wordIndex++;
        }

        // We have reached the end of the paragraph, but the last line of the paragraph probably still needs to be rendered
        if (currentLine.Length > 0)
        {
            // Current text of the line buffer
            string currentLineText = currentLine.ToString();

            // Measure the current line width
            Size currentLineSize = fnt.MeasureText(currentLineText);

            // Draw the text line centering it horizontally
            textGraphics.FillText((pageWidth - currentLineSize.Width) * 0.5, currY, currentLineText, fnt, Colours.Black, TextBaselines.Baseline);

            // Increase the current y coordinate
            currY += fnt.FontSize * 1.4;
        }

        // Optional fancy bit: add some paragraph spacing
        if (i < documentParagraphs.Length - 1)
        {
            currY += fnt.FontSize * 0.7;
        }
    }

    // Now we know that the text has been drawn on textGraphics in an area of width = pageWidth and height ~ currY
    // Therefore, we can use these to center the text on the container page

    Page containerPage = new(800, 300);
    containerPage.Graphics.DrawGraphics((containerPage.Width - pageWidth) * 0.5,
        (containerPage.Height - currY) * 0.5, textGraphics);
    containerPage.SaveAsSVG(Save_SVG_File);

    containerPage.SaveAsPNG(Save_PNG_File, 1);
```

This code should give you something like this:

![SVGCenterText](https://user-images.githubusercontent.com/32712606/129049537-22509e2c-bed2-45a5-bc2a-371a23c2b083.png)

And works also if you have a shorter text:

![SVGCenterText](https://user-images.githubusercontent.com/32712606/129049111-1153f2cc-1971-424e-b1df-7f6aa4826d20.png)

Obviously, you can change the font style and size by changing this line (`20` is the font size, `Helvetica` is the font family - you can change it to `HelveticaBold` or `TimesItalic` or something else):

```CSharp
Font fnt = new Font(new FontFamily(FontFamily.StandardFontFamilies.Helvetica), 20);
```

**Comment by zydjohnHotmail** [comment]
Hello:
Thank you very much for your help.  I tested your code, basically it works.
However, when there are too many words, you can see the text have been truncated.
And I found it is better to adjust the font size to allow more characters.
For example, in my test, if I used font size of 20, then in my page width, the maximum letters can be hold in one line is 88.  And if I used font size of 18, then one line can hold up to 100 letters.
Usually, my text is less than 100 letters, so your code works.
But it is better that the program can adjust the font size to hold, like 100 letters per line.
By the way, how I can set to use Bold for font?
Thanks,
![SVGCenterText](https://user-images.githubusercontent.com/45263518/129054324-d6d535c9-0d1f-4a71-8c95-166ab0fadc2f.png)

**Comment by arklumpus** [comment]
Yeah sorry, I had noticed that the text was too long and shortened it in the code I was actually running, but forgot to update the version I posted here 😅 

If you want to make the text bold, you need to change this line:

```CSharp
Font fnt = new Font(new FontFamily(FontFamily.StandardFontFamilies.Helvetica), 20);
```

To:

```CSharp
Font fnt = new Font(new FontFamily(FontFamily.StandardFontFamilies.HelveticaBold), 20);
```

Have a look at the values of the [`FontFamily.StandardFontFamilies` enum](https://giorgiobianchini.com/VectSharp/class_vect_sharp_1_1_font_family.html#a6cdec4eb0a660064bc416e81f69d3780) for a list of the default fonts that are embedded within VectSharp (or you can just look at them in the Visual Studio IntelliSense popup).

If you wish to use another font, find a font file in TTF format, and use something like this:

```CSharp
Font fnt = new Font(new FontFamily("path\to\font.ttf"), 20);
```

**Comment by zydjohnHotmail** [comment]
Thanks!
