### ISSUE TITLE
Converting png to svg

### ISSUE THREAD

**Issue by Ibel44** [arklumpus/VectSharp#37]
Hello. Very impressive library. I have read the relating parts of the manual and code examples but couldn't pinpoint what I'm doing wrong. I'm trying to convert raster image to svg and export it to a stream. 

After using graphics.DrawRasterImage(0, 0, width, height, rasterImage) and exporting it to a stream with SaveAsSVG(svgStream, SVGContextInterpreter.TextOptions.DoNotEmbed) 2 things happened:

1. If I set the stream position to 0 and use Parser.FromStream(svgStream).SaveAsSVG, the output file shows an error image (red square with x in the middle) instead of the original image. 
2. If instead I convert the stream to a string, remove byte order mark from the beginning and import it to Unity to create a sprite, it partly succeeds but has large black borders like it was not large enough to fill the whole sprite area. A reference svg file downloaded from web worked correctly though.

Do I need MuPDFUtils for this or is it something else that I'm doing wrong?

**Comment by arklumpus** [comment]
Hi! I think the main issue is how you created the RasterImage object - in particular, in what form you have access to the starting image data.

* If you have the image data as an array of RGB or RGBA values (in managed or unmanaged memory), you only need VectSharp (and VectSharp.SVG to export the SVG file):
    ```CSharp
    using VectSharp;
    using VectSharp.SVG;

    byte[] rgbData = ... // Array containing RGB pixel values, this could be also in unmanaged memory.
    int imageWidth = 128;
    int imageHeight = 128;
    PixelFormats pixelFormats = PixelFormats.RGB;

    RasterImage rasterImage = new RasterImage(rgbData, imageWidth, imageHeight, PixelFormats.RGBA, true);
    Page pag = new Page(imageWidth, imageHeight);
    pag.Graphics.DrawRasterImage(0, 0, rasterImage);
    pag.SaveAsSVG("path/to/file.svg");
    ```
    In this case, for a 128x128 pixel image without an alpha channel, `rgbData` should be a `byte` array containing 49'152 elements (i.e., the R, G and B values for each pixel).

* However, if you have the image data in PNG format, you need also VectSharp.MuPDFUtils or VectSharp.ImageSharpUtils to be able to open it. These packages provide the capability to decode the PNG image into raw pixel data (either using MuPDF or ImageSharp):
    ```CSharp
    using VectSharp;
    using VectSharp.SVG;
    using VectSharp.ImageSharpUtils;
    // Or using VectSharp.MuPDFUtils;

    RasterImage rasterImage = new RasterImageFile(@"path/to/file.png");
    Page pag = new Page(rasterImage.Width, rasterImage.Height);
    pag.Graphics.DrawRasterImage(0, 0, rasterImage);
    pag.SaveAsSVG(@"path/to/file.svg");
    ```
    If you have the PNG data in a stream (or in unmanaged memory) instead of a file, you can use the `RasterImageStream` constructor instead of the `RasterImageFile` constructor. 

I hope this makes sense! Let me know if something isn't clear or if you have any more questions!

**Comment by Ibel44** [comment]
Thank you for the quick response. After testing some more I'm starting to think that the issue may be related to Unity's svg import functionality somehow. 

I used raw texture data byte array previously but decided to try using MuPDF and open the file as png directly but the result was the same (large black borders). Perhaps there is some kind of type incompatibility or a setting that I'm not aware of or then something else.

I will mark this issue closed. Thanks again for the help. 🙂
