### ISSUE TITLE
Hello, how to create a two-layer pdf

### ISSUE THREAD

**Issue by lijianxin520** [arklumpus/VectSharp#38]
Hello, how to create a two-layer pdf? The bottom layer is text, and the top layer is pictures.

**Comment by arklumpus** [comment]
Hi! Do you mean a PDF with layers (i.e. "Optional Content") that can be turned on and off in a viewer (like [this]( https://helpx.adobe.com/uk/acrobat/using/pdf-layers.html))? If so, this is currently not implemented in VectSharp.PDF, but I will think about it.

If you just want to draw text and pictures separately and then merge them (without any interactivity on the finished document), you can do this by creating two separate `Graphics` objects, one for text and the other for images, and then using the `Graphics.DrawGraphics` method to draw one on top of the other.

**Comment by lijianxin520** [comment]
Thank you very much for your reply.  What I need is a pdf with layers.  The upper layer is the image and the lower layer is the content.Thank you again!

**Comment by arklumpus** [comment]
Hi! At long last, proper PDF layers (optional content groups) are now fully supported and [documented](https://giorgiobianchini.com/VectSharp/pdf_specific.ocg.html) in VectSharp.PDF 3.0.0!
