### ISSUE TITLE
How to add outlines (bookmarks) in PDF?

### ISSUE THREAD

**Issue by patzhu6426** [arklumpus/VectSharp#39]
When save as PDF, there is not way to add outlines (bookmarks) to the PDF document. Did I miss anything? If not, can you add that feature?

**Comment by arklumpus** [comment]
Hi! No, unfortunately that is currently not possible. I'll see if I can implement it, though!

**Comment by patzhu6426** [comment]
How about a simple way first to bookmark on page? One property Bookmark is added to the Page and Document classes, then Document.SaveAsPDF() looks for the property to create the tree of bookmarks - the Bookmark of Document is the parent.

**Comment by arklumpus** [comment]
This is now implemented in VectSharp.PDF 3.0.0; see the [documentation page](https://giorgiobianchini.com/VectSharp/pdf_specific.outline.html) for more details.

I'm closing this, feel free to reopen it or create a new issue if you have more problems/suggestions!
