### ISSUE TITLE
The issue generated by SaveAsPNG for generating MP4 video.

### ISSUE THREAD

**Issue by zydjohnHotmail** [arklumpus/VectSharp#4]
Hello:
I have used the following C# code to generate one PNG file:
public static async Task CenterTextPNG1Page(string text1, string png_file1)
{
    Font fnt = new(new FontFamily(FontFamily.StandardFontFamilies.CourierBold), 20);
    Graphics textGraphics = new();
    double currY = fnt.FontSize * 1.4;
    if ((text1.Length >= 80) && (text1.Length <= 100))
    {
fnt = new(new FontFamily(FontFamily.StandardFontFamilies.CourierBold), 12);
    }
    Size currentLineSize = fnt.MeasureText(text1);
    textGraphics.FillText((Page_Width - currentLineSize.Width) * 0.5, currY, text1, fnt, Colours.Black, TextBaselines.Baseline);
    currY += fnt.FontSize * 1.4;
    Page containerPage = new(Page_Width, Page_Height);
    containerPage.Graphics.DrawGraphics((containerPage.Width - Page_Width) * 0.5,
(containerPage.Height - currY) * 0.5, textGraphics);
    containerPage.SaveAsPNG(png_file1, 1);
    await Task.Delay(1000);
}

static async Task Main()
{
    await CenterTextPNG1Page("Center Text Test by VectSharp", @"E:\Temp\SVGCenterText.png");
}

I looked at the PNG file, it seems to be OK.
But the funny thing happens, if I run some ffmpeg command to generate a short MP4 video out of this PNG file.
E:\Temp>ffmpeg -loop 1 -i SVGCenterText.png -t 20 SVGCenterText.mp4
The above command generate a short video in MP4 format named:  SVGCenterText.mp4 with duration of 20 seconds, it is based on  SVGCenterText.png.
When I used VLC player to play this video, I see only black/blank screen.
You can see the picture:
![SVGMadeMP4BlankScreen](https://user-images.githubusercontent.com/45263518/129334247-f490ce5c-807d-456c-ace5-34b677d9a151.png)
But if I used Windows built-in tools Paint and open and save as PNG, but gave it another name, like: PaintSVGCenterText.png, then use the following ffmpeg to generate another MP4 video, you can see the video clearly without any issue.
E:\Temp>ffmpeg -loop 1 -i PaintSVGCenterText.png -t 20 PaintSVGCenterText.mp4
You can see the picture:
![PaintMadeMP4FromPNGOK](https://user-images.githubusercontent.com/45263518/129334317-98d94995-1079-438c-953d-f17523357fac.png)
I think there must be some issue with the function: 
ontainerPage.SaveAsPNG(png_file1, 1);
Please check and let me know if I made any mistake in my code.
You can download and install FFMPEG from its this URL: https://ffmpeg.org/download.html
Thanks,

**Comment by arklumpus** [comment]
The issue is very simple: the page has a transparent background (i.e. RGBA = 0,0,0,0), and ffmpeg dumps the alpha channel, which leaves the page with a black background (RGB = 0,0,0 = black). Paint does not support saving PNG files with transparency, so when you open the image with it and save it again, it adds a white background behind the image and makes it opaque.

The solution is equally simple: just add `containerPage.Background = Colours.White;` somewhere before the `SaveAsPNG` line in your code 🙂

**Comment by zydjohnHotmail** [comment]
Thanks!
