### ISSUE TITLE
embed svg in pdf

### ISSUE THREAD

**Issue by patzhu6426** [arklumpus/VectSharp#41]
The following code generates a PDF which cannot be opened by Adobe Acrobat Reader version 2022.003.20282

            Document doc = new Document();
            // add a svg
            Page original = Parser.FromFile("C:\\TestData\\c9c7a515b3.svg");
            
            // Create an page.
            Page page1 = new Page(original.Width + 20, original.Height + 200);
            // draw svg
            page1.Graphics.DrawGraphics(10, 10, original.Graphics);

            FontFamily family = FontFamily.ResolveFontFamily(FontFamily.StandardFontFamilies.Helvetica);
            Font font = new Font(family, 20);

            page1.Graphics.StrokeText(10, original.Height + 20, "Text", font, Colours.Black);

            // Add the page to the document.
            doc.Pages.Add(page1);

            // Save the document as a PDF.
            doc.SaveAsPDF(@"C:\\tmp\\EmbeddedSVG.pdf");

**Comment by arklumpus** [comment]
The code seems fine to me (it works when I try with an SVG file on my machine)... Can you please upload the SVG file you're trying to embed and/or the resulting PDF?

**Comment by patzhu6426** [comment]
[EmbeddedSVG1.pdf](https://github.com/arklumpus/VectSharp/files/10348297/EmbeddedSVG1.pdf)
![c9c7a515b3](https://user-images.githubusercontent.com/120536091/210672273-a1e8e340-07eb-4e72-b19c-8438cf888c4b.svg)

**Comment by patzhu6426** [comment]
I uploaded the PDF and the SVG above.
