### ISSUE TITLE
Pdf issue with Font Family

### ISSUE THREAD

**Issue by patzhu6426** [arklumpus/VectSharp#42]
I saw the code in PdfContext.cs throws exception because the TrueTypeFile is null. I don't understand why and how the FamilyName and FileName are set.

![image](https://user-images.githubusercontent.com/120536091/211053024-66dc2f1b-cbba-4700-a966-4cc0e3d171a1.png)

**Comment by arklumpus** [comment]
Are you using the code I posted in #40 ? You need to change the path to the font files if you do 😅

**Comment by patzhu6426** [comment]
Thanks.
