### ISSUE TITLE
Trade Mark doesn't display properly in PDF

### ISSUE THREAD

**Issue by patzhu6426** [arklumpus/VectSharp#43]
The following code generates good SVG, but in the PDF the TM turns to 42.

            VectSharp.FontFamily.DefaultFontLibrary = new VectSharp.SimpleFontLibrary();
            Page page = new Page(612, 792);
            IEnumerable<FormattedText> formattedText = FormattedText.Format("This is normal MyTradeMark™ string", FontFamily.StandardFontFamilies.Helvetica, 20);
            page.Graphics.FillText(20, 20, formattedText, Colours.Black);

            formattedText = FormattedText.Format("This is bold MyTradeMark™ string", FontFamily.StandardFontFamilies.HelveticaBold, 20);
            page.Graphics.FillText(20, 50, formattedText, Colours.Black);

            formattedText = FormattedText.Format("This is oblique MyTradeMark™ string", FontFamily.StandardFontFamilies.HelveticaOblique, 20);
            page.Graphics.FillText(20, 80, formattedText, Colours.Black);

            formattedText = FormattedText.Format("This is oblique and bold MyTradeMark™ string", FontFamily.StandardFontFamilies.HelveticaBoldOblique, 20);
            page.Graphics.FillText(20, 110, formattedText, Colours.Black);

            page.SaveAsSVG(@"C:\\tmp\\fontStyles.svg");

            Document document = new Document();
            document.Pages.Add(page);
            document.SaveAsPDF(@"C:\\tmp\\fontStyles.pdf");

The SVG, 
![image](https://user-images.githubusercontent.com/120536091/214910812-9ebb39e2-e819-426e-a009-8443b4c3c6c9.png)

The PDF,
![image](https://user-images.githubusercontent.com/120536091/214910176-65c49bfa-b2cd-404d-b40c-fa4aeaba91ca.png)

**Comment by arklumpus** [comment]
Hi! Thank you for noticing this! I have now released version 2.6.1 of VectSharp.PDF (it will take a few minutes to show up on NuGet), which should fix this!

**Comment by patzhu6426** [comment]
Thanks.
