### ISSUE TITLE
PDF file size

### ISSUE THREAD

**Issue by patzhu6426** [arklumpus/VectSharp#44]
I don't know why but I notice the size of the PDF file generated by VectSharp is almost doubled comparing to the PDF file generated by iTextSharp. I basically write text and embed some images in the PDF. The difference on the contents is the format of the images. In VectSharp PDF, svg is used. In iTextSharp, png is used. I noticed the size of the svg image files are actually smaller that the png files - almost half of the size. Do you have any idea about what cause the bigger size?

**Comment by arklumpus** [comment]
Hi! Can you please send me a couple of example files?

**Comment by patzhu6426** [comment]
I will verify with more tests.
