### ISSUE TITLE
SVG rendered with iText 7

### ISSUE THREAD

**Issue by patzhu6426** [arklumpus/VectSharp#45]
I created a SVG with VectSharp. The SVG image has dashed line. The dashed line in PDF appears as solid line. 

The SVG created with VectSharp:
![dashedlinebox](https://user-images.githubusercontent.com/120536091/221071351-d1ad3bbb-19c2-4e91-b60e-a0339dcb974f.svg)

The PDF created with iText 7:
[SVGIssues.pdf](https://github.com/arklumpus/VectSharp/files/10819909/SVGIssues.pdf)

**Comment by arklumpus** [comment]
Can you give me the source code as well, please?

**Comment by arklumpus** [comment]
I'm closing this for now, if you are still working on this and would like to give me a code sample, feel free to reopen and I'd be happy to look into it!
