### ISSUE TITLE
The font Roboto contains a bad /BBox

### ISSUE THREAD

**Issue by vladimir-kazakov** [arklumpus/VectSharp#47]
Using the latest version of `VectSharp` and `VectSharp.PDF`, I've created a PDF with a page that contains a text that uses the Roboto font. When I open it in the latest version of 64-bit Adobe Acrobat Reader for Windows, it shows an informational message in a message box saying `The font 'Roboto' contains a bad /BBox`. The document seems to be displayed correctly, though. Opening it in the latest versions of Firefox and Edge doesn't produce any messages like that.

I've got [the font](https://fonts.google.com/specimen/Roboto) from Google Fonts. It's not installed on my system (the latest version of 64-bit Windows 10 22H2), and I want the behavior of `PDFContextInterpreter.TextOptions.SubsetFonts`. Here's a minimal example that reproduces the issue.

```cs
using VectSharp;
using VectSharp.PDF;

var document = new Document();
var page = new Page(100, 100);
var fontFamily = FontFamily.ResolveFontFamily(Path.Combine("Fonts", "Roboto-Regular.ttf"));
var font = new Font(fontFamily, 50);

page.Graphics.FillText(0, 0, "A", font, Colours.Black);

document.Pages.Add(page);
document.SaveAsPDF("test.pdf");
```

According to some info on the Internet, this should be related to something that creates PDF files. Does it mean that `VectSharp.PDF` is doing something wrong? Or maybe I'm doing something incorrectly? I'm running the code in a console app using the latest version of .NET 6.0.

**Comment by arklumpus** [comment]
Hi! The problem is that the font family is not resolved correctly when the PDF is created, because it has not been cached in the default font library. This should work:

```CSharp
var document = new Document();
var page = new Page(100, 100);
            
// Create a simple font library.
var fontLibrary = new SimpleFontLibrary();
// Set the font library as default.
FontFamily.DefaultFontLibrary = fontLibrary;
// Add the font family to the library.
fontLibrary.Add(FontFamily.ResolveFontFamily(Path.Combine("Fonts", "Roboto-Regular.ttf"));
// Retrieve the font family, you can use either the path again, or just the font family name.
var fontFamily = FontFamily.ResolveFontFamily("Roboto-Regular");

var font = new Font(fontFamily, 50);

page.Graphics.FillText(0, 0, "A", font, Colours.Black);

document.Pages.Add(page);
document.SaveAsPDF(@"C:\Users\Giorgio\Downloads\test.pdf");
```

**Comment by vladimir-kazakov** [comment]
Thanks! I confirm that it solved the problem, so I'm closing this issue.

P.S. Perhaps this could be mentioned in the documentation? Even after re-reading it with this knowledge, it's still unclear that something like that may be needed when dealing with a PDF.

**Comment by arklumpus** [comment]
Yes, you're right! I have actually been thinking for a while of just using a `SimpleLibrary` as default font library and having it cache font families automatically the first time they are resolved (so that you wouldn't need to explicitly call `fontLibrary.Add`), but I need to add a couple of lock statements to keep it thread-safe...
