### ISSUE TITLE
How to convert a SVG file as a PNG file with height and width?

### ISSUE THREAD

**Issue by zydjohnHotmail** [arklumpus/VectSharp#5]
Hello:
I have a few SVG files (around 10), and I want to save them as small PNG files with size of 32 by 32 pixels.
But I don’t have a clear idea on how to do this.
Let’s say, the file is: C:\Temp\1.svg, it is 2KB small SVG file, so I want to covert it to a PNG file named: C:\Temp\1.png with size of 32 by 32 pixels.
I can’t find any code sample for this.  Like how to open it, and set size for PNG file.
Please advise,
Thanks,

**Comment by arklumpus** [comment]
Hi, that should be easy!

You need to install the `VectSharp.SVG` and `VectSharp.Raster` packages, and also the `VectSharp.MuPDFUtils` package if your SVG files contain embedded raster images. Also add the relevant `using` directives.

First of all, setup VectSharp.SVG to open SVG files with embedded raster images (if this is necessary):

```CSharp
Parser.ParseImageURI = ImageURIParser.Parser(Parser.ParseSVGURI);
```

Then, you need to open the SVG file:

```CSharp
Page pag = Parser.FromFile(@"C:\Temp\1.svg");
```

This loads the SVG image into a VectSharp `Page` object.

Finally, you save the `Page` as a PNG image:

```CSharp
pag.SaveAsPNG(@"C:\Temp\1.png", 32 / pag.Width);
```

The trick here is the second argument to the `SaveAsPNG` method, which specifies the factor used to convert VectSharp units (in which the size of the page is expressed) into the pixel-size of the PNG image.
