### ISSUE TITLE
Custom Font - Unicode Character Issue

### ISSUE THREAD

**Issue by broderickt2** [arklumpus/VectSharp#50]
Hello,

I am trying to load a custom font and following the documentation [here](https://giorgiobianchini.com/VectSharp/text.html#custom-fonts-and-font-libraries). I am trying to use `FontFamily.ResolveFontFamily` to load the file. However, I am seeing the error "given key was not present in the dictionary".

I am working in VB.NET, here is the code I am using to reproduce the error:
```
Dim doc = New Document()

doc.Pages.Add(New Page(1000, 1000))

Dim gpr = doc.Pages.Last().Graphics

Dim family = FontFamily.ResolveFontFamily("C:\Vect Test\CabinCondensed-Regular.ttf")

'Dim family = FontFamily.ResolveFontFamily(FontFamily.StandardFontFamilies.Helvetica)  'Runs just fine

Dim Font = New Font(family, 15)

Dim Text = "Test•String"  'Fails because of the bullet point character

Dim textP1 = New Point(76.32, 505.64)
Dim textP2 = New Point(76.32, 207.36)

Dim Path = New GraphicsPath().MoveTo(textP1).LineTo(textP2)

Dim Reference As Double = 0.5

Dim anchor = TextAnchors.Center

gpr.FillTextOnPath(Path, Text, Font, Colours.Black, reference:=Reference, anchor:=anchor, textBaseline:=TextBaselines.Baseline)

doc.SaveAsPDF("C:\Vect Test\Test_VectSharp.pdf")
```

Here is the stack trace of the error:
```
[KeyNotFoundException: The given key was not present in the dictionary.]
   System.ThrowHelper.ThrowKeyNotFoundException() +38
   System.Collections.Generic.Dictionary`2.get_Item(TKey key) +54
   VectSharp.PDF.PDFContextInterpreter.FigureAsPDFString(IFigure figure, Dictionary`2 nonSymbolFontIds, Dictionary`2 symbolFontIds, Dictionary`2 symbolGlyphIndices, Double[] alphas, Dictionary`2 imageObjectNums, Double[,] transformationMatrix, List`1 gradients) +9803
   VectSharp.PDF.PDFContextInterpreter.SaveAsPDF(Document document, Stream stream, TextOptions textOption, Boolean compressStreams, Dictionary`2 linkDestinations, FilterOption filterOption) +18725
   VectSharp.PDF.PDFContextInterpreter.SaveAsPDF(Document document, String fileName, TextOptions textOption, Boolean compressStreams, Dictionary`2 linkDestinations, FilterOption filterOption) +109
```

I believe that the bullet point unicode character is causing this error. If I use "Test String" for `Text`, an error is not thrown. I am using a .ttf file extension so I thought I was setting it up correct, but maybe my file has an issue. I see the documentation advised using Google Fonts; is this because a lot of these types of errors can be avoided by using Google Fonts? I downloaded this particular font from Google Fonts:
[Cabin_Condensed.zip](https://github.com/arklumpus/VectSharp/files/11338495/Cabin_Condensed.zip)

Is my gut feeling correct (my .ttf file has an issue)? I saw something previously in another issue (#48) where multiple fonts were added (ex: the Bold and Italic versions). I am wondering if I need to add them all somehow.

Is there a way to workaround this if the file I am using has an issue? Is there a way to fallback to a standard font family say Helvetica for these unicode character failures only? Any assistance you can provide is much appreciated. Also, let me know if I am misunderstanding how this works.

Thank you in advance for your time and for providing this awesome library!

**Comment by arklumpus** [comment]
Hi! This is basically the same issue as #47 : the font file is fine, you just need to add these lines somewhere before creating the `family` object:

```VB
Dim fontLibrary = New SimpleFontLibrary()
fontLibrary.Add("C:\Vect Test\CabinCondensed-Regular.ttf")
FontFamily.DefaultFontLibrary = fontLibrary
```

Everything should work fine then.

Note that after you add the font to the library, you can either resolve the font family using the path to the TTF file, as you are doing now, or use the font name (`FontFamily.ResolveFontFamily("Cabin Condensed Regular")`), both should work equivalently.

I really need to change the defaults and make this more obvious in the docs 😅

I hope this solves it, let me know if you have any other questions!

**Comment by broderickt2** [comment]
@arklumpus Thanks so much for the quick reply! Your suggestion solved my issue. Also, I agree updating the documentation like you mentioned is a good idea, of course when you get a moment.
