### ISSUE TITLE
Question: Support for Other Vector Formats

### ISSUE THREAD

**Issue by broderickt2** [arklumpus/VectSharp#51]
Hello,

I have looked through the documentation and understand that the vector file types of .PDF and .SVG can be imported using this library, but is there currently any support for other vector types specifically .AI or .EPS files? If these types are not supported, do you have any suggestions or workarounds? I thought about converting .AI or .EPS files to .SVG using another library or tool because then I could import those file types using this library. Also, what about .SVGZ? Is there any support for this?

Thank you in advance for your assistance!

**Comment by arklumpus** [comment]
Hi! Sorry, I forgot to reply to this!

Unfortunately no, I don't have any plans to support AI or EPS files in the library... Converting them to SVG or PDF using other tools might be the best way forward. 

You can import PDFs by converting them to SVG with the [MuPDFCore](https://github.com/arklumpus/MuPDFCore) library (which also comes as a dependency of VectSharp.Raster or VectSharp.MuPDFUtils). The downsides of this are that MuPDFCore has a native library (which may or may not be a problem in your case) and that you need to create a temporary file on disk.

```CSharp
string tempFile = Path.GetTempFileName();

using (MuPDFContext ctx = new MuPDFContext())
using (MuPDFDocument doc = new MuPDFDocument(ctx, "file.pdf")) // You can also use a stream here.
{
    MuPDFDocument.CreateDocument(ctx, tempFile, DocumentOutputFileTypes.SVG, pages: doc.Pages[0]);
}

Page pag = Parser.FromFile(tempFile);
File.Delete(tempFile);
```

Handling SVGZ is easy, as these are just regular SVG files compressed using gzip. For example, to load an SVGZ file:

```CSharp
Page svgzFile;

using (Stream svgzStream = File.OpenRead("conform-viewers-01-t.svgz"))
{
	using (GZipStream decompressionStream = new GZipStream(svgzStream, CompressionMode.Decompress))
	{
		svgzFile = Parser.FromStream(decompressionStream);
	}
}
```
And you can do something similar to export an SVGZ file.

**Comment by broderickt2** [comment]
Hi,

I was thinking the same thing about using other tools to convert other vector types to SVG or PDF. I found some APIs that exist that can do this and will explore those options. I am going to close this issue because I can find a workaround. Thanks for the extra information.
