### ISSUE TITLE
Path figure comprised of arcs not being filled completely

### ISSUE THREAD

**Issue by Moxh3** [arklumpus/VectSharp#58]
I'm trying to create the figure of a [tangent ogive nose cone](https://en.wikipedia.org/wiki/Nose_cone_design). To achieve that, I'm combining two arcs together and adding a backside to complete the shape.

The code I'm using to create the figure looks like:

`path.MoveTo(pTopLeft).Arc(pTopCircleCentre, radius, topStartAngle, topEndAngle).Arc(pBottomCircleCentre, radius, bottomEndAngle, bottomStartAngle).LineTo(pTopLeft).Close();`

When I fill this path, only the arcs get filled, not the whole figure:

![Screenshot 2023-09-26 122431](https://github.com/arklumpus/VectSharp/assets/11796171/616c8ca8-7ca2-490f-a1dd-b58609bcd00f)

I expected that by closing the path, it would be seen as a single path figure, but apparently, it's not.

**Comment by arklumpus** [comment]
Hi, I think you might have something wrong with the angles... What are the values for all the variables? The following works fine to me:

```CSharp
Point pTopLeft = new Point(0, 0);
Point pTopCircleCentre = new Point(0, 128);
double radius = 128;
double topStartAngle = -Math.PI / 2;
double topEndAngle = -Math.PI / 3;
Point pBottomCircleCentre = new Point(0, -128 * (Math.Sqrt(3) - 1));
double bottomEndAngle = Math.PI / 3;
double bottomStartAngle = Math.PI / 2;

GraphicsPath path = new GraphicsPath();
path.MoveTo(pTopLeft).Arc(pTopCircleCentre, radius, topStartAngle, topEndAngle).Arc(pBottomCircleCentre, radius, bottomEndAngle, bottomStartAngle).LineTo(pTopLeft).Close();
```

![test](https://github.com/arklumpus/VectSharp/assets/32712606/3be27d8c-b66e-4a5f-8980-6fd1f3046e31)

**Comment by Moxh3** [comment]
Hi, my values are
`
Point pTopLeft = new Point(44.7, 1.9499999999999997);
Point pTopCircle = new Point(44.7, 31.671491228070156);
double radius = 29.721491228070157;
double topStartAngle = 3 * Math.PI / 2;
double topEndAngle = 5.1538935327710931;
Point pBottomCentreCircle = new Point(44.7, -22.071491228070158)
double bottomEndAngle = 1.1292917744084936;
double bottomStartAngle = Math.PI /2;
`
Could it have to do with the precision, you think?

**Comment by Moxh3** [comment]
If I ensure the X,Y values of all **points** have no more than 2 decimals, it appears to work indeed.

**Comment by arklumpus** [comment]
Ok, I'm officially confused: I tried your values, without changing the number of decimals, and it works fine for me:

<details>
<summary>Open for full code</summary>

```CSharp
using VectSharp;
using VectSharp.PDF;
using VectSharp.Raster;
using VectSharp.Raster.ImageSharp;
using VectSharp.SVG;

Page pag = new Page(100, 10);

Graphics gpr = pag.Graphics;

Point pTopLeft = new Point(44.7, 1.9499999999999997);
Point pTopCircleCentre = new Point(44.7, 31.671491228070156);
double ogiveRadius = 29.721491228070157;
double topStartAngle = 3 * Math.PI / 2;
double topEndAngle = 5.1538935327710931;
Point pBottomCircleCentre = new Point(44.7, -22.071491228070158);
double bottomEndAngle = 1.1292917744084936;
double bottomStartAngle = Math.PI / 2;

GraphicsPath path = new();
path.MoveTo(pTopLeft);
path.Arc(pTopCircleCentre, ogiveRadius, topStartAngle, topEndAngle);
path.Arc(pBottomCircleCentre, ogiveRadius, bottomEndAngle, bottomStartAngle);
path.LineTo(pTopLeft);
path.Close();

gpr.FillPath(path, Colours.Green);
gpr.StrokePath(path, Colours.Black, 0.1);

pag.SaveAsSVG(@"test.svg");
pag.SaveAsImage(@"test.imagesharp.png");
pag.SaveAsPNG(@"test.raster.png");

Document doc = new Document();
doc.Pages.Add(pag);
doc.SaveAsPDF(@"test.pdf");
```

</details>

So, let's troubleshoot:

1. How are you rendering the image? E.g., are you using VectSharp.SVG, VectSharp.PDF, VectSharp.Raster, or something else?
2. What versions of the NuGet packages are you using?
3. Can you please give me a full example of the code that is not working?
4. If you are using VectSharp.SVG or VectSharp.PDF, can you please also upload the SVG/PDF file they produce?

**Comment by Moxh3** [comment]
Sorry, I'm also getting confused, as I can't reproduce the problem anymore. I've removed the number rounding and it continues to work. I'll update this

Just FYI, I'm using VectSharp.SVG (1.8.1) to render with VectSharp 2.4.2.

**Comment by arklumpus** [comment]
Ok, those are the same versions I was using... Please, do reopen this (or a new issue) if you manage to reproduce it again!
