### ISSUE TITLE
using the library from IronPython (unable to save)

### ISSUE THREAD

**Issue by xyont** [arklumpus/VectSharp#59]
hi

i'm interested to use the library from IronPython, it almost works except in saving the drawing. Any hints or suggestion?

regards,

![2023-10-19 06_08_32-test27 py - SciTE](https://github.com/arklumpus/VectSharp/assets/72367311/349f290c-5f03-4557-8b9e-64ad7bdd947e)

**Comment by arklumpus** [comment]
Hi, I'm not familiar with IronPython, but it seems that it does not support calling extension methods like instance methods.

You may need to do something like:

```
VectSharp.SVG.SVGContextInterpreter.SaveAsSVG(page, "Rectangle.svg")
```

You may also need some other `import` statement.
