### ISSUE TITLE
LineDash cannot handle complex patterns

### ISSUE THREAD

**Issue by manutiedra** [arklumpus/VectSharp#67]
There wasn't anything I couldn't do in VectSharp until I found dashed lines with complex patterns like most of:

![image](https://github.com/arklumpus/VectSharp/assets/34885957/d22cd6c8-f127-45f2-ac34-1dde3977b7bf)

Unfortunately, the current implementation of LineDash only lets you specify one "on" and one "off" length. However, SVG lets you specify an array that lets you handle the most complex patterns:

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray

Is there any plan to improve the LineDash to support this?

**Comment by arklumpus** [comment]
Hi! I'm glad VectSharp has been useful to you!

Thank you for pointing this out! The reason I implemented `LineDash` like that is that I though the PDF specification only supports one "on" and one "off" length, but I just realised that this is not the case - it's just that all the examples in the spec document are like that 😅

I will work on the implementation, let's leave this open in the meantime!

**Comment by arklumpus** [comment]
This is now implemented in VectSharp 2.6.0! The `LineDash` constructor now has additional overloads that accept a dash array parameter, which can be used to specify complex dash patterns like the ones above. This is also briefly mentioned [in the docs](https://giorgiobianchini.com/VectSharp/fill_stroke.html).

You can even animate the dash patterns!

![animation](https://github.com/user-attachments/assets/d96f99d0-62cf-41dd-b54e-a62936b7a160)

I'm closing this issue for now, feel free to reopen it (or create a new one) if you see any problems with this or if you have any other question!

**Comment by manutiedra** [comment]
Outstanding work man! Thank you very much
