### ISSUE TITLE
Add DebuggerDisplay attribute to some structs to improve debugging experience

### ISSUE THREAD

**Issue by manutiedra** [arklumpus/VectSharp#70]
While you are debugging, structs like Point, Rectangle, Size, etc. the debugger only shows the namespace and type name:

![image](https://github.com/user-attachments/assets/951a617d-12f4-4b1e-9e77-d9c05ea8a6dc)

However, it will be a lot more useful to show other values without having to open the variable to see its properties (f.e. X and Y values for a point)

You can accomplish that wihe the DebuggerDisplay attribute or with an overriden ToString method. For example:

```cs
public class R1
{
    public double X { get; set; }
    public double Y { get; set; }
}

[DebuggerDisplay("X = {X}, Y = {Y}")]
public class R2
{
    public double X { get; set; }
    public double Y { get; set; }
}
```

If you are debuggin after this code:
```cs
R1 r1 = new R1() { X = 34, Y = 5 };
R2 r2 = new R2() { X = 34, Y = 5 };
```

you get this:
![image](https://github.com/user-attachments/assets/4d695cda-381e-4c5f-a3a2-5c1f171fa241)

**Comment by arklumpus** [comment]
Hi! Sorry, I did this ages ago, but then forgot to push it 😅 In version 2.6.1-a1 I have added `DebuggerDisplay` to all things where I thought it made sense - let me know if I missed anything!

**Comment by manutiedra** [comment]
Sorry for the late reply, but I was on holidays.

It is working great, Thank you
