### ISSUE TITLE
Spacing between letters seems to be wrong

### ISSUE THREAD

**Issue by manutiedra** [arklumpus/VectSharp#73]
I was trying to add some spacing between the letters using a non standard font family and it didn't shown as I expected.

Then I tried the standard font family and it also is not showing as I expected.

Here you can see what I've got using VectSharp:

![image](https://github.com/user-attachments/assets/b9e187f8-11f4-4e04-ba58-8a0d118cff47)

The first font is https://fonts.google.com/specimen/Nova+Square
The second one is FontFamily.StandardFontFamilies.HelveticaBold

If I do the same in illustrator, setting the tracking to a high value I've got this:

![image](https://github.com/user-attachments/assets/a3eee6ae-e67a-4c03-b1c5-73dae1147174)

That looks a lot better. 

I'm drawing the text with VectSharp using:

```cs
TextSpacing spacing = new TextSpacing(spacingScale, 0);
frameContent.FillText(xPos, yPos, text, font, color, spacing: spacing, textBaseline: TextBaselines.Middle);
```

Is the TextSpacing working as expected?
How can I achieve spacing like illustrator does?

**Comment by arklumpus** [comment]
Hi! You probably want to leave the scaling (first parameter to the `TextSpacing` constructor) to 1 and change the increment (i.e. the second parameter instead). For example:

```
TextSpacing spacing = new TextSpacing(1, 3);
frameContent.FillText(xPos, yPos, text, font, color, spacing: spacing, textBaseline: TextBaselines.Middle);
```
This is because if you change the increment, the amount of space that is added is the same for every letter (which is what you want); instead, if you change the scale, the amount of added space is proportional to the letter width (hence, less space is added after `I` than after `A`).

You can have a look at the interactive example [here](https://giorgiobianchini.com/VectSharp/text.html#text-spacing) and see how it works!

**Comment by manutiedra** [comment]
Thank you very much. The second parameter was indeed what I needed. 

I can center the text as I only use the second parameter, taking in account the numer of letters and/or spaces, but I'm wondering how to center it if you want to use both parameters as there is no a TextSpacing parameter for MeasureText and MeasureTextAdvanced. It is not important for me, but I'm just pointing this out.

**Comment by arklumpus** [comment]
Great, glad to hear that helped!

Within the example code in that page, there is some code showing how to measure text with spacing. The trick is creating a `FormattedText` object (where the text spacing can be specified) and putting it into an array. Then you can use the `Measure` extension method that is provided for `IEnumerable<FormattedText>` objects. This produces a `Font.DetailedFontMetrics` object with the text `Width`, `Height`, etc.

```CSharp
// To measure the text with the custom spacing, we need to use a FormattedText object.
double textWidth = new FormattedText[] { new FormattedText(text, fnt, spacing: spacing) }.Measure().Width;
```

**Comment by manutiedra** [comment]
Awesome, thank you!
