### ISSUE TITLE
Invert X/Y Axis

### ISSUE THREAD

**Issue by bennoafk** [arklumpus/VectSharp#74]
I have been using the plotting function and was wondering the best way to "invert" an axis such that up is negative and down is positive.

I have found that creating a LinearCoordinateSystem2D with negative values for scale almost gets there however the position of the chart title is vetically off.

<img width="220" alt="image" src="https://github.com/user-attachments/assets/d925f987-14a8-49d0-a405-e37ddb4a5eef">

Many thanks,
Ben

**Comment by arklumpus** [comment]
Hi, thank you for pointing this out! I have just pushed VectSharp.Plots v1.1.1 (it might take a few minutes for it to show up for you), which should fix the position of the title and the direction of the arrow when the coordinate system is reversed.

I'm not sure how you're reversing the axes, but this is how I would recommend doing it:

```CSharp
// Data points.
double[][] data = Enumerable.Range(0, 61).Select(x => new double[] { x, x * 25 }).ToArray();

// First create a plot with the "normal" axis.
Plot plot = Plot.Create.LineChart(data, xAxisTitle: "Inclination (deg)", yAxisTitle: "Depth (m)", title: "Inclination vs. Depth");

// Get the coordinate system that has been created for the plot.
LinearCoordinateSystem2D coords = plot.GetFirst<LinearCoordinateSystem2D>();

// Reverse the Y axis.
coords.ScaleY *= -1;

// Recreate the plot with exactly the same parameters as before, but this time specify the coordinate system.
plot = Plot.Create.LineChart(data, coordinateSystem: coords, xAxisTitle: "Inclination (deg)", yAxisTitle: "Depth (m)", title: "Inclination vs. Depth");
```

The advantage of this is that the same approach (create plot, get coordinate system, reverse axis, re-create plot with new coordinate system) can be used for all the kinds of plots implemented that can be created by using `Plot.Create...` (e.g., scatter plots, bar charts, violin plots, etc.).

Let me know if you have any questions!

**Comment by bennoafk** [comment]
Hi, Fantastic thank you so much for the code snippet and the quick fix, it works beautifully. It is a brilliant library!

**Comment by arklumpus** [comment]
Great, happy to help!
