### ISSUE TITLE
StackedBarChart fails with one bar

### ISSUE THREAD

**Issue by bennoafk** [arklumpus/VectSharp#75]
Hello,

I seem to have a problem with the stacked bar charts when you only have one dataset.

i.e. the following data source doesn't work:

Random rnd = new Random();
// Note that because of C# tuples are invariant, we have to declare the tuple as
// (string, IReadOnlyList<double>) instead of (string, double[]) - we can still use
// a double[] for the second item of the tuple, though.
(string, IReadOnlyList<double>)[] data = new (string, IReadOnlyList<double>)[] {
    ( "Category 1", new double[] { rnd.Next(1, 10), rnd.Next(1, 10), rnd.Next(1, 10) } ) };

// Create the bar chart using the random data and the default settings.
Plot plot = Plot.Create.StackedBarChart(data);

All the best,
Ben

**Comment by arklumpus** [comment]
Hi! I see you're trying quite a few edge cases 😂

There were a few issues involving divisions by 0 and out of range indices. I just pushed VectSharp.Plots 1.1.**3** which should fix these, and now stacked and clustered bar charts with a single column (group) should work fine.

**Comment by bennoafk** [comment]
Hi, Fantastic it works perfectly now :) Thank you so much!
