### ISSUE TITLE
How to preserve diacritics for NON-English languages in font?

### ISSUE THREAD

**Issue by zydjohnHotmail** [arklumpus/VectSharp#8]
Hello,
I use the following C# code to draw sentence in the center of a PNG image.

`        public static void CenterTextPNG1Page(string text1, string png_file1)
        {
            Font fnt = new(new FontFamily(FontFamily.StandardFontFamilies.CourierBold), 20);
            Graphics textGraphics = new();
            double currY = fnt.FontSize;
            if ((text1.Length >= 60) && (text1.Length <= 100))
            {
                fnt = new(new FontFamily(FontFamily.StandardFontFamilies.CourierBold), 14);
            }
            Size currentLineSize = fnt.MeasureText(text1);
            textGraphics.FillText((B20_Image_Width - currentLineSize.Width) * 0.5,
                                   currY, text1, fnt, Colours.Black, TextBaselines.Baseline);
            Page containerPage = new(B20_Image_Width, 100);
            containerPage.Graphics.DrawGraphics((containerPage.Width - 700) * 0.5,
                (containerPage.Height - currY) * 0.5, textGraphics);
            containerPage.Background = Colours.Green;
            containerPage.SaveAsPNG(png_file1, 1);
        }
`

For English sentence, there is no issue.
But for French or German, all the diacritics are gone.
For example: in French, this sentence “Comme ci comme ça”, meaning “so-so”, the letter ç is totally lost in the generated image.
In German, this sentence “die Bücher”, meaning “the books”, the letter ü is gone.
I want to use ordinary font, which is generally available to all PCs, but keep all the diacritics in the picture.
What I should do?
Thanks,

**Comment by arklumpus** [comment]
Hi, it seems that there is a bug somewhere when subsetting the font. Unfortunately I'm moving house and I can't do an accurate troubleshooting until I get my computer back, but you should be able to work around the bug by replacing this bit:

```CSharp
textGraphics.FillText((700 - currentLineSize.Width) * 0.5, currY, text1, fnt, Colours.Black, TextBaselines.Baseline);
```

With this:

```CSharp
textGraphics.FillPath(new GraphicsPath().AddText((700 - currentLineSize.Width) * 0.5, currY, text1, fnt, TextBaselines.Baseline), Colours.Black);
```

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, your idea works.
Wish you have a good new house for a new life!
